# Generated by Django 3.2.2 on 2023-08-21 00:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Role',
            fields=[
                ('idrole', models.IntegerField(primary_key=True, serialize=False)),
                ('libellerole', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Type',
            fields=[
                ('idtype', models.AutoField(primary_key=True, serialize=False)),
                ('nomtype', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=70, null=True)),
                ('prenom', models.CharField(max_length=70, null=True)),
                ('email', models.CharField(max_length=70, null=True)),
                ('mot_de_passe', models.CharField(max_length=100, null=True)),
                ('service', models.CharField(max_length=100, null=True)),
                ('role', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='login_app.role')),
            ],
        ),
        migrations.CreateModel(
            name='Incident',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('description', models.TextField()),
                ('dateDeclaration', models.DateTimeField()),
                ('detailsreponse', models.TextField(null=True)),
                ('datereparation', models.DateTimeField(null=True)),
                ('type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='login_app.type')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='login_app.user')),
            ],
        ),
    ]
