# Generated by Django 3.2.2 on 2023-08-21 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login_app', '0003_auto_20230821_1759'),
    ]

    operations = [
        migrations.AddField(
            model_name='employe',
            name='service',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
