# Generated by Django 3.2.2 on 2023-08-21 19:11

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('login_app', '0004_employe_service'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employe',
            name='date',
            field=models.DateField(default=django.utils.timezone.now, null=True),
        ),
    ]
