# Generated by Django 3.2.2 on 2023-08-22 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login_app', '0005_alter_employe_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incident',
            name='type',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
