# Generated by Django 3.2.2 on 2023-08-24 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login_app', '0007_alter_incident_datedeclaration'),
    ]

    operations = [
        migrations.AddField(
            model_name='incident',
            name='statut',
            field=models.CharField(choices=[('Nouveau', 'Nouveau'), ('En Cours de Traitement', 'En Cours de Traitement'), ('Résolu', 'Résolu')], default='Nouveau', max_length=100),
        ),
    ]
